name: Convert MusicXML to Notes

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'Path to the MusicXML file'
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install music21
      
      - name: Convert MusicXML to SVG
        run: |
          python -c "from music21 import converter; score = converter.parse('${{ github.event.inputs.file_path }}'); score.write('musicxml.svg', fp='score.svg')"
      
      - name: Upload score SVG
        uses: actions/upload-artifact@v3
        with:
          name: score_svg
          path: score.svg
